sonar.projectKey=sebastiannpy_calidad-software-taller1
sonar.organization=sebastiannpy
sonar.host.url=https://sonarcloud.io

# Rutas
sonar.sources=src
sonar.tests=tests

# Ignorar carpetas
sonar.exclusions=node_modules/**,coverage/**

# Reporte de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8
